libvirt: Fix assignment of PCI addresses
Current code fails with:

Traceback (most recent call last):
  File "/root/github.com/SUSE-Cloud/automation/scripts/lib/libvirt/vm-start", line 16, in <module>
    main()
  File "/root/github.com/SUSE-Cloud/automation/scripts/lib/libvirt/vm-start", line 12, in main
    libvirt_setup.vm_start(args)
  File "/root/github.com/SUSE-Cloud/automation/scripts/lib/libvirt/libvirt_setup.py", line 279, in vm_start
    conn.defineXML(xml)
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 3629, in defineXML
    if ret is None:raise libvirtError('virDomainDefineXML() failed', conn=self)
libvirt.libvirtError: XML error: Invalid PCI address slot='0x30', must be <= 0x1F

So let's just not pick addresses above 0x1F...