Update default platforms and set cache dir for tar_scm
The packages with tar_scm source service are failing because of

1. the default platforms for the respective cloud releases are not
being correctly defined, and
2. for tar_scm, it ran into a nasty error while trying to lookup the
repo cache dir.

File "/usr/lib/obs/service/TarSCM/scm/base.py", line 160, in _calc_repocachedir
    repocachedir = Config().get('tar_scm', 'CACHEDIRECTORY')
...
configparser.DuplicateSectionError: While reading from '<???>' [line  2]: section 'tar_scm' already exists

There's no need to add '[tar_scm]' header as it is accounted for already. See

https://github.com/guangyee/obs-service-tar_scm/blob/master/TarSCM/config.py#L27
https://github.com/guangyee/obs-service-tar_scm/blob/master/TarSCM/config.py#L67-#L70