Skip SUSE-Enterprise-Storage-2-{Pool,Updates} repos check
Fixes:

Error: SUSE-Enterprise-Storage-2-Pool (12.0) does not contain the right \
    repository (/srv/tftpboot/suse-12.0/repos/SUSE-Enterprise-Storage-2-Pool/\
    repodata/repomd.xml is missing repo tag 'obsproduct://build.suse.de/\
    SUSE:SLE-12:Update:Products:Cloud5/ses/2/POOL/x86_64')