devstack: remove python3-pycparser
It gets pulled in via recommends but would later prevent devstack from
installing other things via pip.

Pip would give the following error:
  Attempting uninstall: pycparser
    Found existing installation: pycparser 2.17
ERROR: Cannot uninstall 'pycparser'. It is a distutils installed project
and thus we cannot accurately determine which files belong to it which
would lead to only a partial uninstall.