jenkins: Fix openstack-diskimage-builder job syntax
The wrong syntax was introduced with 4fd4254e89c775 .
This fixes:

yaml.scanner.ScannerError: while scanning a tag
  in "suse-cloud/automation/jenkins/ci.opensuse.org/\
  openstack-diskimage-builder.yaml", line 43, column 27
expected ' ', but found '"'
  in "suse-cloud/automation/jenkins/ci.opensuse.org/\
  openstack-diskimage-builder.yaml", line 43, column 43