remove pointless email section
Newer versions of jjb complain when the email publisher's list of
recipients is empty:

    jenkins_jobs.errors.MissingAttributeError: Missing recipients from an instance of 'publisher.email'