jenkins-job-cancel: handle unicode in job params
Handle unicode values correctly in job parameters.

Cancelling Gerrit jobs is currently failing with:

UnicodeEncodeError: 'ascii' codec can't encode
character u'\xe1' in position 4: ordinal not in range(128)

, because the `jenkins-job-cancel` python script
doesn't handle cases where job parameter values have
unicode characters that cannot be cleanly converted
into ascii.