Enable IPv6 RA accept to have virsh net-start succeed again
Recently IPv6 got enabled on the mkchX hosts, causing all jobs to
fail with the error message:

error: internal error: Check the host setup: enabling IPv6 forwarding
with RA routes without accept_ra set to 2 is likely to cause routes
loss.