Fix renderspec source service handling
This fixes:

     Error: Could not find an xml element with the statement

when only "renderspec" is used as source service.